### ISSUE TITLE
Need help with your JavaScript plugin in a vanilla HTML

### ISSUE THREAD

**Issue by gusbemacbe** [JMHeartley/dTree-Seeder#1]
Good morning!

I use a vanilla HTML instead of an Angular or TpeScript project. I received the following error:

```
dSeeder.js:84 Uncaught Error: Member with id ([object HTMLDivElement]) was not found
    at n (dSeeder.js:84:19)
    at d (dSeeder.js:141:24)
    at e.seed (dSeeder.js:257:25)
    at genealogy-04-dtree.js:32:22dSeeder.js:84 Uncaught Error: Member with id ([object HTMLDivElement]) was not found
    at n (dSeeder.js:84:19)
    at d (dSeeder.js:141:24)
    at e.seed (dSeeder.js:257:25)
    at genealogy-04-dtree.js:32:22
```

Here is a small HTML code:

```html
<link rel="stylesheet" href="assets/css/genealogy-04-dtree.css">
<div id="genealogy"></div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/dtree-seed@1.0.0/dist/dSeeder.min.js"></script>
<script type="text/javascript" src="assets/js/genealogy-04-dtree.js"></script>
```

And a small JavaScript code:

```js
data =
[
	{
		"id": 0,
		"name": "Cláudio César da Costa",
		"class": "man",
		"textClass": "",
		"depthOffset": 1,
		"marriages": 
		[
			{
				"spouse": 
				{
						"id": 1,
						"name": "Tânia Vanessa dos Reis",
						"class": "woman",
						"textClass": "",
						"depthOffset": 1,
						"marriages": [],
						"extra": {}
				}
			}
		],
	}
];

const options =
{
	textClass: "emphasis"
}

seededData = dSeeder.seed(data, genealogy, options);
dTree.init(seededData);
```

**Comment by JMHeartley** [comment]
This plugin is meant to organize the data from a list of member objects. Your `data` isn't set up in that format, and actually looks like it's already in the `seededData` format ready for dTree already.

Also, is that the entire list of members? Without a child to link the parents, the marriage will not be formed.

**Comment by gusbemacbe** [comment]
> Also, is that the entire list of members? Without a child to link the parents, the marriage will not be formed.

Yes. I also made a test with your example samples like https://github.com/JMHeartley/dTree-Seed/blob/main/src/tests/data/dTreeSampleData.json, and the error still is the same:

![image](https://github.com/JMHeartley/dTree-Seed/assets/2257024/6e7c1ca7-0440-4892-9c60-0d21c56bf9df)

You can get my minimal archive and test:

[Genealogia de Gustavo Costa 04 – dTree.zip](https://github.com/JMHeartley/dTree-Seed/files/13401315/Genealogia.de.Gustavo.Costa.04.dTree.zip)

**Comment by JMHeartley** [comment]
Your data object isn't in the `data` format (an array of objects with *certain* properties) as described in the README. Once corrected, you'll get another error because you haven't loaded dTree's dependencies (lodash and d3).

I just forked dTree's JSFiddle and recreated the same output using dTree-Seed to arrange the data. Take a look at it, it may be illuminating https://jsfiddle.net/heartleyjm/zw1ukt60/25/

I also added what `data` might look like for the Examples section in the README and the script tags needed for dTree in the Requirements section. Hopefully, it'll make things clearer for you and others :)

**Comment by gusbemacbe** [comment]
It worked now. Thank you. I have questions about your project.

1. I would like to know if your project can handle a complex family tree. For instance, can I include both my maternal and paternal relatives, such as uncles, aunts, cousins, and their spouses and descendants? Can I also trace back my ancestors up to the 16th generation, along with their siblings, in-laws, children, and descendants?
2. Can I add new person attributes, for example, relationship, and citizenship and ancestries whose values would be emoji flags, and a comment?
3. Can I customise the cards style? For example:

     Drawn on eDrawMax:

     ![Drawn on eDrawMax](https://github.com/JMHeartley/dTree-Seed/assets/2257024/460682c3-3c61-46b3-b6e6-d0f128ce431f)

     Drawn with FamilyTreeJS from Balkan App:

     ![Drawn with FamilyTreeJS from Balkan App](https://github.com/JMHeartley/dTree-Seed/assets/2257024/d66d0e15-dafa-4591-9ef9-f21ef169da52)

     Written in LaTeX and generated with the TeX library `genealogytree`:

     ![Written in LaTeX and generated with the TeX library genealogytree](https://github.com/JMHeartley/dTree-Seed/assets/2257024/0ea377dc-49a1-48f1-9fb8-59d4255b8ce5)

5. Would it be possible to look at the entire genealogy without folding or collapsing?
6. Can I save the entire genealogy in PNG, PDF, and SVG, without folding or collapsing?

**Comment by JMHeartley** [comment]
1. The structure is based on one `marriage`, which is I set as the parent of `target` so you can load their siblings. The direct parents of `target` has to be the end of the structure because this is sneaky coding (on part of dTree) to make this from [d3's tree structure](https://d3js.org/d3-hierarchy/tree). After it loads the direct relatives of `target` it starts loading `target`'s children and from there it loads all descendants up to 100 generations.
2. This plugin is only for arranging the data and doesn't handle what the tree looks like at all. You can custom load the properties from the `data` into `seededData` using `options` but you'd have to configure the display dTree. But, no. I haven't seen those options there either. It gives you the functionality but the display it 100% on you (besides the sample CSS code).
3. See (2).
4. Similar to the above, dTree-Seed doesn't handle any of the looks. It just outputs the whole structure as described in the About section and (1).
5. You would need to figure out how to solve (4) then save as the canvas as SVG or convert it to whatever format you like

**Comment by JMHeartley** [comment]
I'm closing this issue, let me know if you have any other questions.
